spring:

dubbo:
#应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者
  application:
    name: dsp-dubbo-provider
#注册中心配置，用于配置连接注册中心相关信息，zk集群加backup，后面跟从节点用逗号分隔
  registry:
    address: zookeeper://dspzk001:2181?backup=dspzk002:2181,dspzk003:2181
#协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
  protocol:
    name: dubbo
    port: 20880

  server: true

#扫描包
  scan:
    base-packages: com.songheng.dsp.dubbo.provider.partner.serviceImpl


  