spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://10.9.169.172:3306/advertise?characterEncoding=UTF-8&amp;noAccessToProcedureBodies=true
     username: advertmg
     password: d3g7#BN!M8
     type: com.alibaba.druid.pool.DruidDataSource
     filters: stat
     maxActive: 20
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20
#redis信息
  redis:
    hostAndPorts : 10.42.2.149:6379 #暂时未用到 10.42.2.149:6379,10.42.2.149:6379
    pool:
      max-total: 18
      max-active: 18
      max-idle: 18
      max-wait: 100
      min-idle: 0
      timeout: 100
      test-on-borrow : false
      test-on-return : false
      test-while-idle : true
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.dftoutiao.model
hbase:
  linknum: 2
  zookeeper:
    quorum: dftthb2master001.bj2,dftthb2master002.bj2,dftthb2node001.bj2
    pcquorum: dftthbeapp05master001.bj3,dftthbeapp05master002.bj3,dftthbeapp05node001.bj3
    property:
      clientPort: 2181
#钉钉消息通知
msg:
  url: https://oapi.dingtalk.com/robot/send?access_token=%s
  token: 365d83e06e701d318ebb5d60fb118f87a223f75dc8c67fce9e436543a106e841
  mswitch: on
  
  
#COS  
bucketName: dspimg-1256513063
secretId: AKIDQlwvjNpOMAmHbm9ldjjYDk5KNkxzfnQ3
secretKey: vlPZcVHBxYVN4lMn3UkpjqrhKrEPPJ4i
regionName: ap-beijing
dspImgPath: https://dspconf.dftoutiao.com/

#jsonPath
jsonPath: /data/dsptask/advconf/
fileSuffix: .json
filePrefix: conf/