spring:
#数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.185.176:3306/advertise?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: advertmg
    password: SH_xDsk*K@86G#160
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#redis信息
  redis:
     hostAndPorts : 47.98.197.201:6378,47.98.197.201:6379
     pool:
       max-total: 18
       max-active: 18
       max-idle: 18
       max-wait: 100
       min-idle: 0
       timeout: 100
       test-on-borrow : false
       test-on-return : false
       test-while-idle : true
#Mybatis信息
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.dftoutiao.model
#HBASE信息
hbase:
  linknum: 2
  zookeeper:
    quorum: dfmaster001.bj,dfmaster002.bj
    pcquorum: dfmaster001.bj,dfmaster002.bj
    property:
      clientPort: 2181
#钉钉消息通知
msg:
  url: https://oapi.dingtalk.com/robot/send?access_token=%s
  token: ca23858d51e7757265494a8e275bb1586468c584051ffa767893f6b38226b8a1
  mswitch: off

#COS
bucketName: dspimg-1256513063
secretId: AKIDQlwvjNpOMAmHbm9ldjjYDk5KNkxzfnQ3
secretKey: vlPZcVHBxYVN4lMn3UkpjqrhKrEPPJ4i
regionName: ap-beijing
dspImgPath: https://dspconf.dftoutiao.com/

#jsonPath
jsonPath: /data/dsptask/advconf/
fileSuffix: .json
filePrefix: conf/test/

  